### ISSUE TITLE
Can't call method "value" on an undefined value at ./check_homematic line 64

### ISSUE THREAD

**Issue by bdombrowsky** [dkrizic/monitoring-plugins#1]
Hi,

can you please help me with the following error message?

`root@raspi:/opt/homematic# ./check_homematic --host=ccu2 --port=2001 --mode=unreach --level=warning
Can't call method "value" on an undefined value at ./check_homematic line 64.`

Many thanks!

Regards
Benjamin

**Comment by dkrizic** [comment]
I just upgraded from Homegear 5.0 to 6.0 and can reproduce the problems. I will take care in the next days.

**Comment by dkrizic** [comment]
Can you please pull the newest version and try to reproduce. Are you running it against a real CCU2? What software is installed on the CCU? Note: I just have HomeGear which should be compatible. If it does not work, please run it with

-v

and post the output here.

**Comment by dkrizic** [comment]
Thanks. I developed check_homematic against Homegear which should be identical to "original" HomeMatic, but right now I see, that HomeMatic does not provide an "ID" for each device and that subsequent calls are based on ADDRESS, not ID. I have a RaspBi running YAHM, but strangely the XMLRPC does not respond. I will take care of that.

**Comment by bdombrowsky** [comment]
Hi,

in the newest version I've the same error, in a different line:

`root@raspi:/opt/homematic/monitoring-plugins# ./check_homematic --host=ccu2 --port 2001 --mode=lowbat --level=critical
Can't call method "value" on an undefined value at ./check_homematic line 56.`

I've the original CCU2. 

Benjamin

**Comment by dkrizic** [comment]
Can you please check --mode srvmsg if it works. I still have no CCU2 for testing and homegear offers an advanced XML RPC interface.

**Comment by dkrizic** [comment]
If you are willing to help me, please check the newest version with --mode unreach, lowbat and srvmsg

**Comment by janvonde** [comment]
@dkrizic the new version works with unreach, lowbat, pending and srvmsg. Awesome! IMHO this issue can be closed but lets wait for the feedback from @bdombrowsky

**Comment by bdombrowsky** [comment]
Many thanks! Works fine.

**Comment by bdombrowsky** [comment]
One question again, it's a usage problem?

`root@raspi:/opt/homematic/monitoring-plugins# ./check_homematic --host=ccu2 --port 2001 --mode=srvmsg --level=warning
Not an ARRAY reference at ./check_homematic line 62.`

**Comment by dkrizic** [comment]
Happens, when there are no messages, CCU does not return an empty array, but something else, I will take a look

**Comment by dkrizic** [comment]
Please check again ,should work now. Can you please also check --mode unreach and lowbat and if it does not work, give me the output of -v.

**Comment by bdombrowsky** [comment]
Hi,

all modes are working now for me (Original CCU2 with newest firmware).

Many thanks!

**Comment by dkrizic** [comment]
Can you do some counter testing, e.g. plugging out a device and checking, that there is an unreach? I will close for now and please reopen if something is not working.

**Comment by bdombrowsky** [comment]
Hi,

wir können scheinbar auch auf deutsch schreiben...

Also, was mir noch aufgefallen ist, war bei einer leeren Batterie von meinem Heizungsthermostat. Dies wurde korrekt via Servicemeldung ausgegeben, aber nicht bei dem Batterie Check berücksichtigt. 

Ein unreached Device werde ich noch mal versuchen nachzustellen. 

Gruß
Benni

**Comment by dkrizic** [comment]
Ich habe folgendes Problem: Das gesamte Homematic-Zeug arbeitet mit Addresses. Homegear arbeitet zusätzlich mit IDs. Unterschiede gibt es bei den Folgemethoden: Homegear erwartet die ID, die CCU2 erwartet die Address, wobei die Doku nie sagt, ob das jetzt mit channel oder ohne ist (XXXX:Y oder nur XXXX). Da ich auch nicht weiss, was die CCU2 genau für eine Meldung ausgibt, wenn die address nicht stimmt, habe ich keine klare Fehlerbehandlung eingebaut, daher brauche ich die Ausgabe mit -v, diese enthält den Dump.

**Comment by janvonde** [comment]
@dkrizic. Danke für dein Engagement uns zu helfen bei einem Problem, dass Du selbst nicht nachstellen kannst.

Verstehe ich es richtig, dass Du gerade einem Dump mit -v benötigst wärend ein Gerät eine lowbattery Meldung gibt?

**Comment by dkrizic** [comment]
Das wäre super

**Comment by janvonde** [comment]
Alles klar. Falls @bdombrowsky nicht schneller ist :wink: suche ich heute Abend mal ne leere Batterie und probiere einen zu machen.

**Comment by chrostek** [comment]
Hallo,

ich habe auch eine "originale" CCU2 (YAHM) und das Problem, dass außer dem Mode srvmsg nichts sauber funktioniert (ich bekomme zwar keine Fehler angezeigt, aber im Verbose sieht man Fehler und die Werte (unreach, pending, lowbat) haben alle den Wert "undef". Ich habe mit dieser Änderung Erfolg gehabt (ich kann nicht wirklich Perl programmieren, daher bitte auf jeden Fall nochmal prüfen):

printf "Reading details for %i devices\n",scalar keys %address if $verbose;
foreach my $address (keys %address) {
    my $id = $address;
    my @msg;
    if( $address{$address}->{'id'} ){
        $id = $address{$address}->{'id'};
        push @msg, RPC::XML::int->new( $id );
        push @msg, RPC::XML::int->new( 0 );
        push @msg, RPC::XML::string->new( 'VALUES' );
    } else {
        push @msg, RPC::XML::string->new( $id.":0" );
        push @msg, RPC::XML::string->new( 'VALUES' );
        push @msg, RPC::XML::int->new( 0 );
    }
    my $resp = $cli->send_request('getParamset',@msg);
    print Dumper( $resp ) if $verbose;
    $address{$address}->{'unreach'} = $resp->value->{'UNREACH'};
    $address{$address}->{'lowbat'} = $resp->value->{'LOWBAT'};
    $address{$address}->{'pending'} = $resp->value->{'CONFIG_PENDING'};
}

Kurze Erklärung:

Bei der CCU2 scheint es wie von euch vermutet so zu sein, dass man den Channel (ich vermute mal für die hier gebrauchten Werte immer Channel 0) anhängen muss, daher:

 push @msg, RPC::XML::string->new( $id.":0" );

Weiterhin ist die ID ein String und kein INT:

push @msg, RPC::XML::string->new( $id );

Das if/else habe ich eingebaut, da bei der CCU auch die Reihenfolge der Parameter unterschiedlich ist:

Paramset getParamset(String address, String paramset_key,
Integer mode)

Siehe auch 4.2.6: http://www.eq-3.de/Downloads/Software/HM-CCU2-Firmware_Updates/Tutorials/HM_XmlRpc_API.pdf

Ich hoffe, dass ich damit etwas helfen konnte. Bei mir funktioniert es so wunderbar :-)

**Comment by janvonde** [comment]
@chrostek kannst Du das als Pull request hier einreichen? Dann würde ich das auch testen :wink:

**Comment by chrostek** [comment]
@janvonde Habs hinbekommen :-) auch mit GitHub kenne ich mich kaum aus ... :-)

**Comment by janvonde** [comment]
@chrostek Danke. Mit den Änderungen funktionieren meine Checks weiterhin.

@dkrizic Mit den Änderungen ist auch mein lowbat Problem bei dem die Devices nicht erkannt wurden behoben.

> OK: All 17 battery powered devices with sufficient batteries | 'Low battery'=0
