### ISSUE TITLE
homematic: getServiceMessages

### ISSUE THREAD

**Issue by janvonde** [dkrizic/monitoring-plugins#3]
It would be awesome if you could support the getServiceMessages xml rpc call like OK if empty and warning or critical if there is a value...

**Comment by dkrizic** [comment]
Good idea, I will take a look

**Comment by dkrizic** [comment]
Ok, please check --mode srvmsg

**Comment by janvonde** [comment]
That works! really cool feature!

**Comment by janvonde** [comment]
Just a minor suggestion. Line 67 comment out the print. Otherwise it will look like this:

> me@hs2 ~ $ ./check_homematic --host=ccu2.home --port 2001 --mode=srvmsg --level=warning
> LEQ0143580:0 = UNREACH
> LEQ0538921:0 = STICKY_UNREACH
> LEQ1174022:0 = STICKY_UNREACH
> WARNING: Devices have service messages: UNREACH (LEQ0143580:0), STICKY_UNREACH (LEQ0538921:0, LEQ1174022:0)

**Comment by janvonde** [comment]
Another addition: If there are no service messages I get the following error:

> me@hs2 ~ $ ./check_homematic --host=ccu2.home --port 2001 --mode=srvmsg --level=warning
> Not an ARRAY reference at ./check_homematic line 62.
> me@hs2 ~ $

**Comment by dkrizic** [comment]
Pull request is merged, above bug should also be fixed now.
